### ISSUE TITLE
Help on building this on linux

### ISSUE THREAD

**Issue by faxm0dem** [Ellerbach/LegoDimensions#16]
Hi,

I never used mono on linux, could you please give a few instructions on how to build the project ?

Thanks !

**Comment by Ellerbach** [comment]
You don't need mono. All will work with .NET 6.0.
If you are running a RaspberryPi or another arm device, you already have an artifact which contains everything you need.
Otherwise, just install .NET 6.0. See https://dotnet.microsoft.com/en-us/download/dotnet/6.0
You don't need to build for a specific platform, just build normally on your Windows machine with Visual Studio for example (or VS Code) with .NET 6.0 or higher installed. Select "Any CPU". Then you just have to copy the built files to your Linux machine.

**Comment by faxm0dem** [comment]
I don't have a windows machine - so this is a requirement for building ?

**Comment by Ellerbach** [comment]
> I don't have a windows machine - so this is a requirement for building ?

No, you can build on any platform. See the pointer on how to install .NET 6.0, it's available on Windows, Mac OS and Linux. Depending on the development tool you'll be using, building can be a bit different. `dotnet build` with the name of the sln project is enough from a command line (you'll build in debug by default)

**Comment by faxm0dem** [comment]
Thanks, it's clearer now.
I'll try it out
